[package]
name = "yd_lib_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding = "0.2.33"
memchr = "2.3.3"
simple-error = "0.3.0"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
bindgen = "0.69.4"
